### ISSUE TITLE
Cutting Board recipe from Farmer's Delight - By theq_continuum

### ISSUE THREAD

**Issue by dctime** [dctime/progress-through-skies-modpack#1]
So I'm not sure if I'm just missing something somewhere. But I am having trouble trying to find how to make a Cutting Board so that I can start getting flint. Maybe I'm just blind. But I've looked everywhere. Thanks for your time.

**Comment by dctime** [comment]
You can break gravel normally to get flint :). JEI doesn't show block loot tables. The cutting board recipe is just for testing. I'll remove the recipe in the next update and add a note of making flint.

**Comment by TheeQContinuum** [comment]
Thanks I was going to try that but thought that maybe you had another way to do that. Now I'm going to sound like an idiot. But I am also having some issue planting and growing the Demon's Dream Seed so I can get the fruit from it.

**Comment by dctime** [comment]
You can modify hammer in tetra. :) Use a hammer to modify another hammer.
