### ISSUE TITLE
soul sand

### ISSUE THREAD

**Issue by cdawg2403** [dctime/progress-through-skies-modpack#2]
no way of knowing how to get soul sand

**Comment by dctime** [comment]
![image](https://github.com/dctime/progress-through-skies-modpack/assets/48884643/765fee2f-b977-48b1-ab89-0b0b7b764cef)

The ritual is different from the previous ritual which makes click machine. I will add some description to the quest.
You can google "Eziveus' Spectral Compulsion" to know how to draw the ritual.
![image](https://github.com/dctime/progress-through-skies-modpack/assets/48884643/5ea0d7b9-775c-43b2-8bb9-68fab0609ae1)

If there is something I missed, reply and show me where it goes wrong to your progress. :)

**Comment by dctime** [comment]
Oh, remember to put the sacrifice stuff first then the main item. It will refuse you to put the main item first.
