### ISSUE TITLE
Growing/Farmland

### ISSUE THREAD

**Issue by Stoettho** [dctime/progress-through-skies-modpack#3]
Dear Folks,

maybe I am missing something but I am looking since 30 minutes how to grow things?

How do I progress to soul fire? I already have the seeds.

**Comment by Stoettho** [comment]
Modifie Hammer with Hammer :D

**Comment by dctime** [comment]
I really need to fix this. :|

**Comment by dctime** [comment]
Added note to the quest. Ready to launch in the newest update.
