### ISSUE TITLE
Snow spawn biome locks progression?

### ISSUE THREAD

**Issue by amberemeny** [dctime/progress-through-skies-modpack#5]
Testing out the modpack for the first time, spawned in Snowy Taiga biome. Used the rain wand, it started snowing.. no rain for the barrels :( 

Keen to play after more updates!

**Comment by dctime** [comment]
Thank you for reporting :) I never thought about this before. I'll fix it in the next update.

**Comment by dctime** [comment]
Bug fixed! Added to the new update.
